// The hymnal. Edit here, then run: node tools/build-hymns.js
//
// Only hymns whose words were published before 1928 (public domain), chosen
// from the hymns sung in Independent Baptist churches. Left out on purpose:
// texts still under copyright (How Great Thou Art, Victory in Jesus, Great Is
// Thy Faithfulness outside the US), Catholic-origin texts other than Christmas
// carols (Faith of Our Fathers, Be Thou My Vision), Marian hymns, Unitarian
// authors, and texts that teach sinless perfection (Love Divine, All Loves
// Excelling). Christmas carols of older Catholic origin (Silent Night, O Come
// All Ye Faithful, O Come O Come Emmanuel) ARE included: their words are about
// the Lord's birth, not prayers to Mary.
//
// [title, author, year, category, refs]
// The words are in tools/hymns/texts.json, keyed by title.
module.exports = [
  // ── Praise and Worship
  ['Holy, Holy, Holy', 'Reginald Heber', 1826, 'Praise and Worship', 'Isaiah 6:3; Revelation 4:8'],
  ['O Worship the King', 'Robert Grant', 1833, 'Praise and Worship', 'Psalm 104:1-5'],
  ["All Hail the Power of Jesus' Name", 'Edward Perronet', 1779, 'Praise and Worship', 'Philippians 2:9-11; Revelation 19:16'],
  ['Crown Him with Many Crowns', 'Matthew Bridges', 1851, 'Praise and Worship', 'Revelation 19:12'],
  ['O for a Thousand Tongues to Sing', 'Charles Wesley', 1739, 'Praise and Worship', 'Psalm 35:28'],
  ['To God Be the Glory', 'Fanny J. Crosby', 1875, 'Praise and Worship', 'Galatians 1:5; John 3:16'],
  ['Praise Him! Praise Him!', 'Fanny J. Crosby', 1869, 'Praise and Worship', 'Psalm 150:6'],
  ['Blessed Be the Name', 'William H. Clark', 1888, 'Praise and Worship', 'Psalm 72:19'],
  ['Guide Me, O Thou Great Jehovah', 'William Williams', 1745, 'Praise and Worship', 'Exodus 13:21; Psalm 48:14'],
  ['Rejoice, the Lord Is King', 'Charles Wesley', 1744, 'Praise and Worship', 'Philippians 4:4'],
  ['Jesus Shall Reign', 'Isaac Watts', 1719, 'Praise and Worship', 'Psalm 72:8'],
  ['Come, Thou Fount of Every Blessing', 'Robert Robinson', 1758, 'Praise and Worship', '1 Samuel 7:12'],
  // ── The Blood and the Cross
  ['Nothing but the Blood', 'Robert Lowry', 1876, 'The Blood and the Cross', 'Hebrews 9:22; 1 John 1:7'],
  ['There Is Power in the Blood', 'Lewis E. Jones', 1899, 'The Blood and the Cross', 'Revelation 12:11'],
  ['When I Survey the Wondrous Cross', 'Isaac Watts', 1707, 'The Blood and the Cross', 'Galatians 6:14'],
  ['The Old Rugged Cross', 'George Bennard', 1913, 'The Blood and the Cross', '1 Corinthians 1:18'],
  ['At Calvary', 'William R. Newell', 1895, 'The Blood and the Cross', 'Luke 23:33'],
  ['At the Cross', 'Isaac Watts', 1707, 'The Blood and the Cross', 'Isaiah 53:5'],
  ['Jesus Paid It All', 'Elvina M. Hall', 1865, 'The Blood and the Cross', 'Isaiah 1:18'],
  ['Rock of Ages', 'Augustus M. Toplady', 1776, 'The Blood and the Cross', '1 Corinthians 10:4; Isaiah 26:4'],
  ['There Is a Fountain', 'William Cowper', 1772, 'The Blood and the Cross', 'Zechariah 13:1'],
  ['When I See the Blood', 'John G. Foote', 1892, 'The Blood and the Cross', 'Exodus 12:13'],
  ['Are You Washed in the Blood?', 'Elisha A. Hoffman', 1878, 'The Blood and the Cross', 'Revelation 7:14'],
  ['Grace Greater than Our Sin', 'Julia H. Johnston', 1911, 'The Blood and the Cross', 'Romans 5:20'],
  ['Redeemed', 'Fanny J. Crosby', 1882, 'The Blood and the Cross', 'Psalm 107:2; 1 Peter 1:18-19'],
  ['Wonderful Grace of Jesus', 'Haldor Lillenas', 1918, 'The Blood and the Cross', 'Ephesians 2:8'],
  // ── Salvation and Invitation
  ['Amazing Grace', 'John Newton', 1779, 'Salvation and Invitation', 'Ephesians 2:8; 1 Chronicles 17:16'],
  ['Just As I Am', 'Charlotte Elliott', 1835, 'Salvation and Invitation', 'John 6:37'],
  ['Softly and Tenderly', 'Will L. Thompson', 1880, 'Salvation and Invitation', 'Matthew 11:28'],
  ['Whosoever Will', 'Philip P. Bliss', 1870, 'Salvation and Invitation', 'Revelation 22:17'],
  ['Pass Me Not', 'Fanny J. Crosby', 1868, 'Salvation and Invitation', 'Luke 18:38'],
  ['Almost Persuaded', 'Philip P. Bliss', 1871, 'Salvation and Invitation', 'Acts 26:28'],
  ['Christ Receiveth Sinful Men', 'Erdmann Neumeister', 1718, 'Salvation and Invitation', 'Luke 15:2'],
  ['Ye Must Be Born Again', 'William T. Sleeper', 1877, 'Salvation and Invitation', 'John 3:7'],
  ['Why Do You Wait?', 'George F. Root', 1878, 'Salvation and Invitation', '2 Corinthians 6:2'],
  ['Where Will You Spend Eternity?', 'Elisha A. Hoffman', 1878, 'Salvation and Invitation', 'Matthew 25:46'],
  ['Let Jesus Come into Your Heart', 'Lelia N. Morris', 1898, 'Salvation and Invitation', 'Revelation 3:20'],
  ['Since Jesus Came into My Heart', 'Rufus H. McDaniel', 1914, 'Salvation and Invitation', '2 Corinthians 5:17'],
  ['Love Lifted Me', 'James Rowe', 1912, 'Salvation and Invitation', 'Psalm 40:2'],
  // ── Assurance and Trust
  ['Blessed Assurance', 'Fanny J. Crosby', 1873, 'Assurance and Trust', 'Hebrews 10:22'],
  ['I Know Whom I Have Believed', 'Daniel W. Whittle', 1883, 'Assurance and Trust', '2 Timothy 1:12'],
  ['The Solid Rock', 'Edward Mote', 1834, 'Assurance and Trust', 'Matthew 7:24-25; 1 Corinthians 3:11'],
  ['Standing on the Promises', 'R. Kelso Carter', 1886, 'Assurance and Trust', '2 Peter 1:4'],
  ["'Tis So Sweet to Trust in Jesus", 'Louisa M. R. Stead', 1882, 'Assurance and Trust', 'Proverbs 3:5'],
  ['Trust and Obey', 'John H. Sammis', 1887, 'Assurance and Trust', '1 Samuel 15:22'],
  ['Leaning on the Everlasting Arms', 'Elisha A. Hoffman', 1887, 'Assurance and Trust', 'Deuteronomy 33:27'],
  ['He Leadeth Me', 'Joseph H. Gilmore', 1862, 'Assurance and Trust', 'Psalm 23:2'],
  ['All the Way My Saviour Leads Me', 'Fanny J. Crosby', 1875, 'Assurance and Trust', 'Psalm 48:14'],
  ['What a Friend We Have in Jesus', 'Joseph M. Scriven', 1855, 'Assurance and Trust', 'Proverbs 18:24; Philippians 4:6'],
  ['Does Jesus Care?', 'Frank E. Graeff', 1901, 'Assurance and Trust', '1 Peter 5:7'],
  ['Leave It There', 'Charles A. Tindley', 1916, 'Assurance and Trust', 'Psalm 55:22'],
  ['Count Your Blessings', 'Johnson Oatman Jr.', 1897, 'Assurance and Trust', 'Psalm 103:2'],
  ['Will Your Anchor Hold?', 'Priscilla J. Owens', 1882, 'Assurance and Trust', 'Hebrews 6:19'],
  ['He Hideth My Soul', 'Fanny J. Crosby', 1890, 'Assurance and Trust', 'Exodus 33:22'],
  ['It Is Well with My Soul', 'Horatio G. Spafford', 1873, 'Assurance and Trust', '2 Kings 4:26'],
  // ── The Christian Life
  ['I Surrender All', 'Judson W. Van DeVenter', 1896, 'The Christian Life', 'Romans 12:1'],
  ['Take My Life and Let It Be', 'Frances R. Havergal', 1874, 'The Christian Life', 'Romans 12:1'],
  ['Have Thine Own Way, Lord', 'Adelaide A. Pollard', 1907, 'The Christian Life', 'Jeremiah 18:6'],
  ['I Need Thee Every Hour', 'Annie S. Hawks', 1872, 'The Christian Life', 'John 15:5'],
  ['Higher Ground', 'Johnson Oatman Jr.', 1898, 'The Christian Life', 'Philippians 3:14'],
  ['Draw Me Nearer', 'Fanny J. Crosby', 1875, 'The Christian Life', 'James 4:8'],
  ['Where He Leads Me', 'E. W. Blandly', 1890, 'The Christian Life', 'Luke 9:23'],
  ['Stand Up, Stand Up for Jesus', 'George Duffield Jr.', 1858, 'The Christian Life', 'Ephesians 6:13-14'],
  ['Take Time to Be Holy', 'William D. Longstaff', 1882, 'The Christian Life', '1 Peter 1:16'],
  ['More About Jesus', 'Eliza E. Hewitt', 1887, 'The Christian Life', '2 Peter 3:18'],
  ['Yield Not to Temptation', 'Horatio R. Palmer', 1868, 'The Christian Life', '1 Corinthians 10:13'],
  ['Blest Be the Tie That Binds', 'John Fawcett', 1782, 'The Christian Life', 'Ephesians 4:3; Galatians 6:2'],
  // ── Soulwinning and Missions
  ['Rescue the Perishing', 'Fanny J. Crosby', 1869, 'Soulwinning and Missions', 'Jude 1:22-23'],
  ['Bringing in the Sheaves', 'Knowles Shaw', 1874, 'Soulwinning and Missions', 'Psalm 126:6'],
  ['Send the Light', 'Charles H. Gabriel', 1890, 'Soulwinning and Missions', 'Acts 13:47; Matthew 5:16'],
  ['Let the Lower Lights Be Burning', 'Philip P. Bliss', 1871, 'Soulwinning and Missions', 'Matthew 5:16'],
  ['I Love to Tell the Story', 'A. Katherine Hankey', 1866, 'Soulwinning and Missions', 'Psalm 66:16'],
  ['Tell Me the Old, Old Story', 'A. Katherine Hankey', 1866, 'Soulwinning and Missions', '1 Corinthians 15:3-4'],
  ['The Ninety and Nine', 'Elizabeth C. Clephane', 1868, 'Soulwinning and Missions', 'Luke 15:4'],
  ['Throw Out the Life-Line', 'Edward S. Ufford', 1888, 'Soulwinning and Missions', 'Jude 1:23'],
  ['Jesus Saves', 'Priscilla J. Owens', 1882, 'Soulwinning and Missions', 'Isaiah 62:11; Romans 10:13'],
  ['To the Work', 'Fanny J. Crosby', 1869, 'Soulwinning and Missions', 'John 9:4'],
  // ── Prayer and the Word
  ['Sweet Hour of Prayer', 'William W. Walford', 1845, 'Prayer and the Word', 'Matthew 6:6'],
  ['I Must Tell Jesus', 'Elisha A. Hoffman', 1893, 'Prayer and the Word', 'Hebrews 4:16'],
  ['Did You Think to Pray?', 'Mary A. Kidder', 1876, 'Prayer and the Word', '1 Thessalonians 5:17'],
  ['Wonderful Words of Life', 'Philip P. Bliss', 1874, 'Prayer and the Word', 'John 6:68'],
  ['Holy Bible, Book Divine', 'John Burton', 1803, 'Prayer and the Word', 'Psalm 119:105'],
  ['Thy Word Have I Hid in My Heart', 'Ernest O. Sellers', 1908, 'Prayer and the Word', 'Psalm 119:11, 105'],
  // ── Heaven and His Coming
  ['When We All Get to Heaven', 'Eliza E. Hewitt', 1898, 'Heaven and His Coming', 'John 14:2-3'],
  ['When the Roll Is Called Up Yonder', 'James M. Black', 1893, 'Heaven and His Coming', '1 Thessalonians 4:16-17'],
  ['In the Sweet By and By', 'S. Fillmore Bennett', 1868, 'Heaven and His Coming', 'Hebrews 11:16'],
  ['Face to Face', 'Carrie E. Breck', 1898, 'Heaven and His Coming', '1 Corinthians 13:12'],
  ['Christ Returneth', 'H. L. Turner', 1878, 'Heaven and His Coming', 'Acts 1:11'],
  ['Is It the Crowning Day?', 'George W. Whitcomb', 1913, 'Heaven and His Coming', 'Titus 2:13'],
  ["There's a Great Day Coming", 'Will L. Thompson', 1887, 'Heaven and His Coming', 'Matthew 25:31-32'],
  ['Shall We Gather at the River?', 'Robert Lowry', 1864, 'Heaven and His Coming', 'Revelation 22:1'],
  // ── Christmas and Easter
  ['Joy to the World', 'Isaac Watts', 1719, 'Christmas and Easter', 'Psalm 98:4-9'],
  ['Hark! the Herald Angels Sing', 'Charles Wesley', 1739, 'Christmas and Easter', 'Luke 2:13-14'],
  ['Angels from the Realms of Glory', 'James Montgomery', 1816, 'Christmas and Easter', 'Luke 2:8-15'],
  ['O Little Town of Bethlehem', 'Phillips Brooks', 1868, 'Christmas and Easter', 'Micah 5:2'],
  ['Away in a Manger', 'Anonymous', 1885, 'Christmas and Easter', 'Luke 2:7'],
  ['Christ the Lord Is Risen Today', 'Charles Wesley', 1739, 'Christmas and Easter', 'Matthew 28:6'],
  ['Low in the Grave He Lay', 'Robert Lowry', 1874, 'Christmas and Easter', 'Luke 24:6'],
  // ── Added later. New hymns go at the END of this list so that a hymn keeps its place in notes and shared links;
  //    the Hymns page groups them under their sections by the category (4th field).
  ['Praise to the Lord, the Almighty', 'Joachim Neander', 1680, 'Praise and Worship', 'Psalm 103:1-5; Psalm 150:6'],
  ['Revive Us Again', 'William P. Mackay', 1863, 'Praise and Worship', 'Psalm 85:6'],
  ['Immortal, Invisible, God Only Wise', 'Walter C. Smith', 1867, 'Praise and Worship', '1 Timothy 1:17'],
  ['All People That on Earth Do Dwell', 'William Kethe', 1561, 'Praise and Worship', 'Psalm 100:1-5'],
  ['A Mighty Fortress Is Our God', 'Martin Luther', 1529, 'Praise and Worship', 'Psalm 46:1'],
  ['Praise, My Soul, the King of Heaven', 'Henry F. Lyte', 1834, 'Praise and Worship', 'Psalm 103:1-5'],
  ['Come, Thou Almighty King', 'Anonymous', 1757, 'Praise and Worship', 'Jude 1:25'],
  ['The God of Abraham Praise', 'Thomas Olivers', 1770, 'Praise and Worship', 'Exodus 3:6'],
  ['My Jesus, I Love Thee', 'William R. Featherston', 1864, 'Praise and Worship', '1 John 4:19'],
  ['How Sweet the Name of Jesus Sounds', 'John Newton', 1779, 'Praise and Worship', 'Song of Solomon 1:3'],
  ['Take the Name of Jesus with You', 'Lydia Baxter', 1870, 'Praise and Worship', 'Acts 4:12'],
  ['Majestic Sweetness Sits Enthroned', 'Samuel Stennett', 1787, 'Praise and Worship', 'Song of Solomon 5:16'],
  ['Jesus, Lover of My Soul', 'Charles Wesley', 1740, 'Praise and Worship', 'Psalm 18:2'],
  ['Praise God, from Whom All Blessings Flow', 'Thomas Ken', 1674, 'Praise and Worship', 'Psalm 150:6'],
  ['The Church’s One Foundation', 'Samuel J. Stone', 1866, 'Praise and Worship', '1 Corinthians 3:11'],
  ['O God, Our Help in Ages Past', 'Isaac Watts', 1719, 'Praise and Worship', 'Psalm 90:1-2'],
  ['Ye Servants of God', 'Charles Wesley', 1744, 'Praise and Worship', 'Psalm 113:1-3'],
  ['Hail to the Lord’s Anointed', 'James Montgomery', 1821, 'Praise and Worship', 'Psalm 72:1-8'],
  ['Hail, Thou Once Despised Jesus', 'John Bakewell', 1757, 'Praise and Worship', 'Hebrews 7:25'],
  ['Come, Let Us Join Our Cheerful Songs', 'Isaac Watts', 1707, 'Praise and Worship', 'Revelation 5:11-12'],
  ['Join All the Glorious Names', 'Isaac Watts', 1709, 'Praise and Worship', 'Philippians 2:9-11'],
  ['O How I Love Jesus', 'Frederick Whitfield', 1855, 'Praise and Worship', '1 John 4:19'],
  ['All Things Bright and Beautiful', 'Cecil F. Alexander', 1848, 'Praise and Worship', 'Genesis 1:31'],
  ['Alas! and Did My Saviour Bleed?', 'Isaac Watts', 1707, 'The Blood and the Cross', 'Isaiah 53:5'],
  ['And Can It Be?', 'Charles Wesley', 1738, 'The Blood and the Cross', 'Romans 8:1; Acts 16:26'],
  ['Not All the Blood of Beasts', 'Isaac Watts', 1709, 'The Blood and the Cross', 'Hebrews 10:4'],
  ['Beneath the Cross of Jesus', 'Elizabeth C. Clephane', 1868, 'The Blood and the Cross', 'Isaiah 32:2'],
  ['Near the Cross', 'Fanny J. Crosby', 1869, 'The Blood and the Cross', 'John 19:25'],
  ['Man of Sorrows! What a Name', 'Philip P. Bliss', 1875, 'The Blood and the Cross', 'Isaiah 53:3'],
  ['I Will Sing of My Redeemer', 'Philip P. Bliss', 1877, 'The Blood and the Cross', 'Psalm 71:23'],
  ['Hiding in Thee', 'William O. Cushing', 1876, 'The Blood and the Cross', 'Psalm 61:2'],
  ['I Lay My Sins on Jesus', 'Horatius Bonar', 1843, 'The Blood and the Cross', 'Isaiah 53:6'],
  ['There Is a Green Hill Far Away', 'Cecil F. Alexander', 1848, 'The Blood and the Cross', 'Luke 23:33'],
  ['I Stand Amazed in the Presence', 'Charles H. Gabriel', 1905, 'The Blood and the Cross', 'Romans 5:8'],
  ['A Debtor to Mercy Alone', 'Augustus M. Toplady', 1771, 'The Blood and the Cross', 'Titus 3:5'],
  ['Ivory Palaces', 'Henry Barraclough', 1915, 'The Blood and the Cross', 'Psalm 45:8'],
  ['Lord, I’m Coming Home', 'William J. Kirkpatrick', 1892, 'Salvation and Invitation', 'Luke 15:18'],
  ['I Heard the Voice of Jesus Say', 'Horatius Bonar', 1846, 'Salvation and Invitation', 'Matthew 11:28'],
  ['Hark, My Soul! It Is the Lord', 'William Cowper', 1768, 'Salvation and Invitation', 'John 21:16'],
  ['O Happy Day That Fixed My Choice', 'Philip Doddridge', 1755, 'Salvation and Invitation', 'Joshua 24:15'],
  ['Grace! ’Tis a Charming Sound', 'Philip Doddridge', 1755, 'Salvation and Invitation', 'Ephesians 2:8'],
  ['I’ve Found a Friend, O Such a Friend!', 'James G. Small', 1863, 'Salvation and Invitation', 'John 15:15'],
  ['The Lily of the Valley', 'Charles W. Fry', 1881, 'Salvation and Invitation', 'Song of Solomon 2:1'],
  ['Jesus Calls Us', 'Cecil F. Alexander', 1852, 'Salvation and Invitation', 'Mark 1:17'],
  ['Peace, Perfect Peace', 'Edward H. Bickersteth', 1875, 'Assurance and Trust', 'Isaiah 26:3'],
  ['Be Not Dismayed Whate’er Betide', 'Civilla D. Martin', 1904, 'Assurance and Trust', '1 Peter 5:7'],
  ['Safe in the Arms of Jesus', 'Fanny J. Crosby', 1868, 'Assurance and Trust', 'Deuteronomy 33:27'],
  ['Anywhere with Jesus', 'Jessie B. Pounds', 1887, 'Assurance and Trust', 'Psalm 139:9-10'],
  ['Saviour, Like a Shepherd Lead Us', 'Dorothy A. Thrupp', 1836, 'Assurance and Trust', 'Isaiah 40:11'],
  ['The Lord’s My Shepherd, I’ll Not Want', 'Francis Rous', 1650, 'Assurance and Trust', 'Psalm 23:1-6'],
  ['The King of Love My Shepherd Is', 'Henry W. Baker', 1868, 'Assurance and Trust', 'Psalm 23:1-6'],
  ['God Moves in a Mysterious Way', 'William Cowper', 1773, 'Assurance and Trust', 'Romans 11:33'],
  ['How Firm a Foundation', 'John Rippon’s Selection', 1787, 'Assurance and Trust', 'Isaiah 41:10'],
  ['Jesus, I Am Resting, Resting', 'Jean S. Pigott', 1876, 'Assurance and Trust', 'Psalm 116:7'],
  ['Like a River Glorious', 'Frances R. Havergal', 1874, 'Assurance and Trust', 'Isaiah 48:18'],
  ['Simply Trusting Every Day', 'Edgar P. Stites', 1876, 'Assurance and Trust', 'Psalm 56:3'],
  ['O Love That Wilt Not Let Me Go', 'George Matheson', 1882, 'Assurance and Trust', 'Romans 8:38-39'],
  ['Under His Wings', 'William O. Cushing', 1896, 'Assurance and Trust', 'Psalm 91:4'],
  ['Abide with Me', 'Henry F. Lyte', 1847, 'Assurance and Trust', 'Luke 24:29'],
  ['The Day Thou Gavest, Lord, Is Ended', 'John Ellerton', 1870, 'Assurance and Trust', 'Psalm 74:16'],
  ['Beulah Land', 'Edgar P. Stites', 1876, 'Assurance and Trust', 'Isaiah 62:4'],
  ['In the Garden', 'C. Austin Miles', 1912, 'Assurance and Trust', 'John 20:15-16'],
  ['His Eye Is on the Sparrow', 'Civilla D. Martin', 1905, 'Assurance and Trust', 'Matthew 10:29-31'],
  ['The Love of God', 'Frederick M. Lehman', 1917, 'Assurance and Trust', '1 John 4:8'],
  ['Master, the Tempest Is Raging', 'Mary Ann Baker', 1874, 'Assurance and Trust', 'Mark 4:39'],
  ['Sweet Peace, the Gift of God’s Love', 'Peter P. Bilhorn', 1892, 'Assurance and Trust', 'John 14:27'],
  ['It Passeth Knowledge', 'Mary Shekleton', 1863, 'Assurance and Trust', 'Ephesians 3:19'],
  ['O Jesus, I Have Promised', 'John E. Bode', 1868, 'The Christian Life', 'John 12:26'],
  ['Fight the Good Fight', 'John S. B. Monsell', 1863, 'The Christian Life', '1 Timothy 6:12'],
  ['Onward, Christian Soldiers', 'Sabine Baring-Gould', 1865, 'The Christian Life', '2 Timothy 2:3'],
  ['Jesus, I My Cross Have Taken', 'Henry F. Lyte', 1824, 'The Christian Life', 'Luke 9:23'],
  ['O to Be Like Thee', 'Thomas O. Chisholm', 1897, 'The Christian Life', '1 John 3:2'],
  ['Dare to Be a Daniel', 'Philip P. Bliss', 1873, 'The Christian Life', 'Daniel 1:8'],
  ['Brighten the Corner Where You Are', 'Ina D. Ogdon', 1912, 'The Christian Life', 'Matthew 5:16'],
  ['I Gave My Life for Thee', 'Frances R. Havergal', 1858, 'The Christian Life', '1 Peter 1:18-19'],
  ['Saviour, Thy Dying Love', 'S. Dryden Phelps', 1862, 'The Christian Life', 'Psalm 116:12'],
  ['I Am Thine, O Lord', 'Fanny J. Crosby', 1875, 'The Christian Life', 'Psalm 116:16'],
  ['Just as I Am, Thine Own to Be', 'Marianne Farningham', 1887, 'The Christian Life', 'Psalm 116:16'],
  ['Jesus Bids Us Shine', 'Susan Warner', 1868, 'The Christian Life', 'Matthew 5:14'],
  ['Jesus Loves Me', 'Anna B. Warner', 1860, 'The Christian Life', 'Matthew 19:14'],
  ['I Think When I Read That Sweet Story of Old', 'Jemima Luke', 1841, 'The Christian Life', 'Mark 10:14'],
  ['God Be with You Till We Meet Again', 'Jeremiah E. Rankin', 1880, 'The Christian Life', 'Numbers 6:24-26'],
  ['Let Others See Jesus in You', 'B. B. McKinney', 1924, 'The Christian Life', '1 Peter 2:12'],
  ['Jesus Is the Sweetest Name I Know', 'Lela B. Long', 1924, 'The Christian Life', 'Philippians 2:9'],
  ['Teach Me Thy Way, O Lord', 'B. Mansell Ramsey', 1919, 'The Christian Life', 'Psalm 27:11'],
  ['Loving Shepherd of Thy Sheep', 'Jane E. Leeson', 1842, 'The Christian Life', 'John 10:11'],
  ['Gentle Jesus, Meek and Mild', 'Charles Wesley', 1742, 'The Christian Life', 'Mark 10:14'],
  ['The Way of the Cross Leads Home', 'Jessie B. Pounds', 1906, 'The Christian Life', 'Luke 9:23'],
  ['I Will Sing the Wondrous Story', 'Francis H. Rowley', 1886, 'The Christian Life', 'Psalm 71:16'],
  ['O the Deep, Deep Love of Jesus', 'S. Trevor Francis', 1875, 'The Christian Life', 'Ephesians 3:18-19'],
  ['Hold the Fort', 'Philip P. Bliss', 1870, 'The Christian Life', 'Revelation 2:25'],
  ['From Greenland’s Icy Mountains', 'Reginald Heber', 1819, 'Soulwinning and Missions', 'Mark 16:15'],
  ['Must I Go and Empty-Handed?', 'Charles C. Luther', 1877, 'Soulwinning and Missions', 'Proverbs 11:30'],
  ['Go, Labour On', 'Horatius Bonar', 1843, 'Soulwinning and Missions', 'John 9:4'],
  ['Lord, Speak to Me, That I May Speak', 'Frances R. Havergal', 1872, 'Soulwinning and Missions', 'Isaiah 6:8'],
  ['Break Thou the Bread of Life', 'Mary A. Lathbury', 1877, 'Prayer and the Word', 'John 6:35'],
  ['Open My Eyes, That I May See', 'Clara H. Scott', 1895, 'Prayer and the Word', 'Psalm 119:18'],
  ['From Every Stormy Wind That Blows', 'Hugh Stowell', 1828, 'Prayer and the Word', 'Hebrews 4:16'],
  ['Prayer Is the Soul’s Sincere Desire', 'James Montgomery', 1818, 'Prayer and the Word', 'Luke 11:1'],
  ['’Tis the Blessed Hour of Prayer', 'Fanny J. Crosby', 1880, 'Prayer and the Word', 'Matthew 6:6'],
  ['Father of Mercies, in Thy Word', 'Anne Steele', 1760, 'Prayer and the Word', 'Psalm 119:105'],
  ['Lord, Thy Word Abideth', 'Henry W. Baker', 1861, 'Prayer and the Word', '1 Peter 1:25'],
  ['Come, My Soul, Thy Suit Prepare', 'John Newton', 1779, 'Prayer and the Word', 'Matthew 7:7'],
  ['There Shall Be Showers of Blessing', 'Daniel W. Whittle', 1883, 'Prayer and the Word', 'Ezekiel 34:26'],
  ['For Ever with the Lord', 'James Montgomery', 1835, 'Heaven and His Coming', '1 Thessalonians 4:17'],
  ['When This Passing World Is Done', 'Robert Murray McCheyne', 1837, 'Heaven and His Coming', '1 Corinthians 13:12'],
  ['On Jordan’s Stormy Banks', 'Samuel Stennett', 1787, 'Heaven and His Coming', 'Joshua 3:17'],
  ['Asleep in Jesus', 'Margaret Mackay', 1832, 'Heaven and His Coming', '1 Thessalonians 4:14'],
  ['Lo! He Comes with Clouds Descending', 'Charles Wesley', 1758, 'Heaven and His Coming', 'Revelation 1:7'],
  ['Thou Art Coming, O My Saviour', 'Frances R. Havergal', 1870, 'Heaven and His Coming', 'Titus 2:13'],
  ['Saviour, More than Life to Me', 'Fanny J. Crosby', 1875, 'Heaven and His Coming', 'John 15:4'],
  ['The First Noel', 'Traditional English', 1823, 'Christmas and Easter', 'Luke 2:8-14'],
  ['What Child Is This?', 'William C. Dix', 1865, 'Christmas and Easter', 'Luke 2:11-12'],
  ['While Shepherds Watched Their Flocks', 'Nahum Tate', 1700, 'Christmas and Easter', 'Luke 2:8-14'],
  ['As with Gladness Men of Old', 'William C. Dix', 1860, 'Christmas and Easter', 'Matthew 2:9-11'],
  ['O Come, All Ye Faithful', 'Frederick Oakeley', 1841, 'Christmas and Easter', 'Luke 2:15'],
  ['O Come, O Come, Emmanuel', 'John Mason Neale', 1851, 'Christmas and Easter', 'Isaiah 7:14'],
  ['Silent Night', 'Joseph Mohr', 1818, 'Christmas and Easter', 'Luke 2:7-14'],
  ['O Holy Night', 'John S. Dwight', 1855, 'Christmas and Easter', 'Luke 2:10-11'],
  ['We Three Kings of Orient Are', 'John H. Hopkins Jr.', 1857, 'Christmas and Easter', 'Matthew 2:1-11'],
  ['Angels We Have Heard on High', 'Traditional French', 1862, 'Christmas and Easter', 'Luke 2:13-14'],
  ['God Rest Ye Merry, Gentlemen', 'Traditional English', 1833, 'Christmas and Easter', 'Luke 2:10-11'],
  ['Go, Tell It on the Mountain', 'John W. Work Jr.', 1907, 'Christmas and Easter', 'Luke 2:10-11'],
  ['Were You There?', 'African American spiritual', 1899, 'Christmas and Easter', 'Matthew 27:35'],
  ['The Lord Is Risen Indeed', 'Thomas Kelly', 1820, 'Christmas and Easter', 'Luke 24:34'],
  ['Good Christian Friends, Rejoice', 'John Mason Neale', 1853, 'Christmas and Easter', 'Luke 2:10-11'],
];
