# Journey stops draft: (place name as in places.json, verse, short note). '~' prefix = route waypoint only
J = {
 "abraham": ("Abraham's journey", "Genesis 11–25", [
  ("Ur","Genesis 11:31","Terah takes Abram out of Ur of the Chaldees"),
  ("Haran","Genesis 11:31","They come to Haran and dwell there"),
  ("Shechem","Genesis 12:6","Abram passes through the land unto Sichem"),
  ("Bethel","Genesis 12:8","An altar between Bethel and Hai"),
  ("Egypt","Genesis 12:10","Down into Egypt in the famine"),
  ("Bethel","Genesis 13:3","Back to the place of the altar"),
  ("Hebron","Genesis 13:18","He dwells in the plain of Mamre"),
  ("Dan","Genesis 14:14","He pursues the kings unto Dan"),
  ("Hobah","Genesis 14:15","Hobah, on the left hand of Damascus"),
  ("Salem","Genesis 14:18","Melchizedek king of Salem"),
  ("Gerar","Genesis 20:1","He sojourns in Gerar"),
  ("Beersheba","Genesis 21:31","The well of the oath"),
  ("Moriah","Genesis 22:2","Get thee into the land of Moriah"),
  ("Beersheba","Genesis 22:19","They return to Beersheba"),
  ("Hebron","Genesis 23:19","Sarah buried in the cave of Machpelah"),
 ]),
 "jacob": ("Jacob's journey", "Genesis 28–35, 46", [
  ("Beersheba","Genesis 28:10","Jacob goes out from Beersheba"),
  ("Bethel","Genesis 28:19","The ladder; he calls the place Bethel"),
  ("Haran","Genesis 29:4","Twenty years with Laban"),
  ("Gilead","Genesis 31:25","Laban overtakes him in mount Gilead"),
  ("Mahanaim","Genesis 32:2","The angels of God meet him"),
  ("Peniel","Genesis 32:30","He wrestles until the breaking of the day"),
  ("Succoth","Genesis 33:17","He builds booths"),
  ("Shechem","Genesis 33:18","He comes to Shalem, a city of Shechem"),
  ("Bethel","Genesis 35:6","He builds an altar at Bethel"),
  ("Bethlehem","Genesis 35:19","Rachel dies on the way to Ephrath"),
  ("Hebron","Genesis 35:27","He comes unto Isaac at Mamre"),
  ("Beersheba","Genesis 46:1","Sacrifices on the way to Egypt"),
  ("Goshen","Genesis 46:28","Joseph meets him in Goshen"),
 ]),
 "joseph": ("Joseph sold into Egypt", "Genesis 37", [
  ("Hebron","Genesis 37:14","Sent out of the vale of Hebron"),
  ("Shechem","Genesis 37:14","To see his brethren at Shechem"),
  ("Dothan","Genesis 37:17","He finds them in Dothan"),
  ("Egypt","Genesis 37:28","Sold to the Ishmeelites and brought into Egypt"),
 ]),
 "exodus": ("The Exodus & the wilderness", "Exodus 12 – Deuteronomy 34", [
  ("Rameses","Exodus 12:37","Israel journeys from Rameses"),
  ("Succoth","Exodus 12:37","To Succoth"),
  ("Etham","Exodus 13:20","Encamped in Etham, in the edge of the wilderness"),
  ("Pi-hahiroth","Exodus 14:2","Before Pi-hahiroth — the Red Sea is parted"),
  ("Marah","Exodus 15:23","The bitter waters made sweet"),
  ("Elim","Exodus 15:27","Twelve wells and seventy palm trees"),
  ("Sin","Exodus 16:1","The wilderness of Sin — manna given"),
  ("Rephidim","Exodus 17:1","Water from the rock; Amalek fought"),
  ("Mount Sinai","Exodus 19:20","The LORD comes down upon mount Sinai"),
  ("Kibroth-hattaavah","Numbers 11:34","The graves of lust"),
  ("Hazeroth","Numbers 11:35","Miriam's leprosy"),
  ("Kadesh","Numbers 13:26","The spies return; forty years decreed"),
  ("Ezion-geber","Numbers 33:35","Encamped at Ezion-gaber"),
  ("Hor","Numbers 20:27","Aaron dies in mount Hor"),
  ("Punon","Numbers 33:42","Encamped in Punon"),
  ("Arnon","Numbers 21:13","Beyond Arnon, the border of Moab"),
  ("Heshbon","Numbers 21:26","Sihon's city taken"),
  ("Plains of Moab","Numbers 22:1","The plains of Moab by Jordan near Jericho"),
  ("Nebo","Deuteronomy 34:1","Moses sees the land and dies"),
 ]),
 "david": ("David fleeing Saul", "1 Samuel 19–27", [
  ("Gibeah","1 Samuel 22:6","Saul abides in Gibeah"),
  ("Ramah","1 Samuel 19:18","David escapes to Samuel at Ramah"),
  ("Nob","1 Samuel 21:1","Ahimelech gives him the shewbread"),
  ("Gath","1 Samuel 21:10","He flees to Achish king of Gath"),
  ("Adullam","1 Samuel 22:1","The cave Adullam"),
  ("Mizpeh","1 Samuel 22:3","Mizpeh of Moab"),
  ("Hareth","1 Samuel 22:5","The forest of Hareth"),
  ("Keilah","1 Samuel 23:5","He saves Keilah"),
  ("Wilderness of Ziph","1 Samuel 23:14","The wilderness of Ziph"),
  ("Wilderness of Maon","1 Samuel 23:25","The wilderness of Maon"),
  ("Engedi","1 Samuel 24:1","He spares Saul in the cave"),
  ("Carmel","1 Samuel 25:2","Nabal and Abigail"),
  ("Gath","1 Samuel 27:2","Back to Achish"),
  ("Ziklag","1 Samuel 27:6","Achish gives him Ziklag"),
 ]),
 "elijah": ("Elijah", "1 Kings 17 – 2 Kings 2", [
  ("Tishbite","1 Kings 17:1","Elijah the Tishbite"),
  ("Cherith","1 Kings 17:3","Fed by ravens at the brook"),
  ("Zarephath","1 Kings 17:9","The widow's meal and oil"),
  ("Carmel","1 Kings 18:20","Fire from heaven on mount Carmel"),
  ("Kishon","1 Kings 18:40","The prophets of Baal slain"),
  ("Jezreel","1 Kings 18:46","He runs before Ahab to Jezreel"),
  ("Beersheba","1 Kings 19:3","He flees for his life"),
  ("Horeb","1 Kings 19:8","The still small voice"),
  ("Abel-meholah","1 Kings 19:16","Elisha of Abel-meholah called"),
  ("Gilgal","2 Kings 2:1","With Elisha from Gilgal"),
  ("Bethel","2 Kings 2:2","To Bethel"),
  ("Jericho","2 Kings 2:4","To Jericho"),
  ("Jordan","2 Kings 2:7","Taken up by a whirlwind beyond Jordan"),
 ]),
 "jonah": ("Jonah", "Jonah 1–4", [
  ("Gath-hepher","2 Kings 14:25","Jonah the prophet, of Gath-hepher"),
  ("Joppa","Jonah 1:3","He takes ship at Joppa, fleeing toward Tarshish"),
  ("Nineveh","Jonah 3:3","Nineveh, that great city, repents"),
 ]),
 "captivity": ("Carried away to Babylon", "2 Kings 24–25; Daniel 1", [
  ("Jerusalem","2 Kings 25:9","The house of the LORD burnt"),
  ("Riblah","2 Kings 25:6","Zedekiah judged at Riblah"),
  ("~Carchemish","","(route along the Euphrates)"),
  ("Babylon","2 Kings 25:11","The people carried away to Babylon"),
  ("Chebar","Ezekiel 1:1","Ezekiel among the captives by the river Chebar"),
  ("Shushan","Daniel 8:2","Daniel's vision at Shushan the palace"),
 ]),
 "return": ("The return from captivity", "Ezra – Nehemiah", [
  ("Babylon","Ezra 1:11","Cyrus sends them up from Babylon"),
  ("Ahava","Ezra 8:15","Ezra gathers them by the river Ahava"),
  ("~Carchemish","","(route along the Euphrates)"),
  ("Jerusalem","Ezra 8:32","They come to Jerusalem"),
  ("Shushan","Nehemiah 1:1","Nehemiah in Shushan the palace"),
  ("Jerusalem","Nehemiah 2:11","Nehemiah comes to Jerusalem and builds the wall"),
 ]),
 "childhood": ("The birth and childhood of Jesus", "Matthew 2; Luke 2", [
  ("Nazareth","Luke 2:4","Joseph goes up from Nazareth"),
  ("Bethlehem","Luke 2:4","The Saviour born in Bethlehem"),
  ("Jerusalem","Luke 2:22","Presented to the Lord in the temple"),
  ("Egypt","Matthew 2:14","The flight into Egypt"),
  ("Nazareth","Matthew 2:23","He dwells in Nazareth"),
  ("Jerusalem","Luke 2:42","In the temple at twelve years old"),
 ]),
 "ministry": ("Jesus' ministry", "the Gospels", [
  ("Bethabara","John 1:28","Baptized beyond Jordan"),
  ("Cana","John 2:1","Water made wine"),
  ("Capernaum","John 2:12","Down to Capernaum"),
  ("Jerusalem","John 2:13","The temple cleansed; Nicodemus"),
  ("Sychar","John 4:5","The woman at the well"),
  ("Cana","John 4:46","The nobleman's son healed"),
  ("Nazareth","Luke 4:16","Rejected in his own synagogue"),
  ("Capernaum","Matthew 4:13","He dwells in Capernaum"),
  ("Nain","Luke 7:11","The widow's son raised"),
  ("Gadarenes","Mark 5:1","The man with the legion"),
  ("Bethsaida","Luke 9:10","Five thousand fed"),
  ("Tyre","Mark 7:24","The Syrophenician woman"),
  ("Sidon","Mark 7:31","Through the coasts of Tyre and Sidon"),
  ("Caesarea Philippi","Matthew 16:13","“Thou art the Christ”"),
  ("Capernaum","Matthew 17:24","The tribute money"),
  ("Bethany","John 11:1","Lazarus raised"),
  ("Ephraim","John 11:54","He goes to a city called Ephraim"),
 ]),
 "passion": ("The last week & the resurrection", "the Gospels; Acts 1", [
  ("Jericho","Luke 19:1","Zacchaeus"),
  ("Bethany","John 12:1","Six days before the passover"),
  ("Bethphage","Matthew 21:1","The colt brought from Bethphage"),
  ("Jerusalem","Matthew 21:10","The triumphal entry"),
  ("Gethsemane","Matthew 26:36","He prays in the garden"),
  ("Golgotha","John 19:17","Crucified at the place of a skull"),
  ("Emmaus","Luke 24:13","The road to Emmaus"),
  ("Sea of Galilee","John 21:1","He shows himself by the sea"),
  ("Mount of Olives","Acts 1:12","Taken up from the mount called Olivet"),
 ]),
 "paul0": ("Saul's conversion", "Acts 9, 11; Galatians 1", [
  ("Jerusalem","Acts 9:2","Breathing out threatenings"),
  ("Damascus","Acts 9:3","A light from heaven"),
  ("Arabia","Galatians 1:17","I went into Arabia"),
  ("Damascus","Acts 9:22","Let down by the wall in a basket"),
  ("Jerusalem","Acts 9:26","Barnabas brings him to the apostles"),
  ("Caesarea","Acts 9:30","Brought down to Caesarea"),
  ("Tarsus","Acts 9:30","Sent forth to Tarsus"),
  ("Antioch","Acts 11:26","Called Christians first in Antioch"),
 ]),
 "peter": ("Philip and Peter", "Acts 8–10", [
  ("Jerusalem","Acts 8:1","The church scattered"),
  ("Samaria","Acts 8:5","Philip preaches Christ in Samaria"),
  ("Gaza","Acts 8:26","The way that goeth down unto Gaza — the eunuch"),
  ("Ashdod","Acts 8:40","Philip found at Azotus","Azotus"),
  ("Lod","Acts 9:32","Peter heals Aeneas","Lydda"),
  ("Joppa","Acts 9:36","Dorcas raised"),
  ("Caesarea","Acts 10:24","Cornelius and his house saved"),
 ]),
 "paul1": ("Paul's first journey", "Acts 13–14", [
  ("Antioch","Acts 13:1","Separated for the work"),
  ("Seleucia","Acts 13:4","Down to Seleucia"),
  ("Salamis","Acts 13:5","Preaching in the synagogues"),
  ("Paphos","Acts 13:6","Elymas the sorcerer blinded"),
  ("Perga","Acts 13:13","John departs from them"),
  ("Antioch","Acts 13:14","“Lo, we turn to the Gentiles”","Antioch in Pisidia"),
  ("Iconium","Acts 13:51","A great multitude believe"),
  ("Lystra","Acts 14:8","The cripple healed; Paul stoned"),
  ("Derbe","Acts 14:20","Many taught"),
  ("Lystra","Acts 14:21","Confirming the souls of the disciples"),
  ("Attalia","Acts 14:25","Down into Attalia"),
  ("Antioch","Acts 14:26","Back to Antioch"),
 ]),
 "paul2": ("Paul's second journey", "Acts 15:36 – 18:22", [
  ("Antioch","Acts 15:35","Paul and Silas set out"),
  ("Derbe","Acts 16:1","Timothy joins them"),
  ("Troas","Acts 16:8","The vision of the man of Macedonia"),
  ("Samothracia","Acts 16:11","A straight course to Samothracia"),
  ("Neapolis","Acts 16:11","To Neapolis"),
  ("Philippi","Acts 16:12","Lydia; the jailer saved"),
  ("Amphipolis","Acts 17:1","Through Amphipolis"),
  ("Thessalonica","Acts 17:1","Three sabbath days reasoning"),
  ("Berea","Acts 17:10","They searched the scriptures daily"),
  ("Athens","Acts 17:22","Mars' hill"),
  ("Corinth","Acts 18:1","A year and six months"),
  ("Cenchrea","Acts 18:18","Shorn his head at Cenchrea"),
  ("Ephesus","Acts 18:19","Reasoning with the Jews"),
  ("Caesarea","Acts 18:22","Landed at Caesarea"),
  ("Antioch","Acts 18:22","Down to Antioch"),
 ]),
 "paul3": ("Paul's third journey", "Acts 18:23 – 21:17", [
  ("Antioch","Acts 18:22","Some time at Antioch"),
  ("Ephesus","Acts 19:1","Two years; the uproar of Diana"),
  ("Troas","Acts 20:6","Eutychus raised"),
  ("Assos","Acts 20:13","Paul goes afoot to Assos"),
  ("Mitylene","Acts 20:14","To Mitylene"),
  ("Miletus","Acts 20:17","Farewell to the Ephesian elders"),
  ("Coos","Acts 21:1","A straight course unto Coos"),
  ("Rhodes","Acts 21:1","To Rhodes"),
  ("Patara","Acts 21:1","To Patara"),
  ("Tyre","Acts 21:3","Seven days with the disciples"),
  ("Ptolemais","Acts 21:7","To Ptolemais"),
  ("Caesarea","Acts 21:8","Philip's house; Agabus"),
  ("Jerusalem","Acts 21:17","Received gladly"),
 ]),
 "rome": ("Paul's voyage to Rome", "Acts 21–28", [
  ("Jerusalem","Acts 21:31","Paul taken in the temple"),
  ("Aphek","Acts 23:31","Brought by night to Antipatris","Antipatris"),
  ("Caesarea","Acts 23:33","Two years before Felix and Festus"),
  ("Sidon","Acts 27:3","Julius lets him visit his friends"),
  ("Myra","Acts 27:5","A ship of Alexandria"),
  ("Cnidus","Acts 27:7","Scarce come over against Cnidus"),
  ("Salmone","Acts 27:7","Under Crete, over against Salmone"),
  ("The fair havens","Acts 27:8","Near the city of Lasea"),
  ("Clauda","Acts 27:16","Under the island Clauda — the storm"),
  ("Melita","Acts 28:1","Shipwrecked on Melita"),
  ("Syracuse","Acts 28:12","Three days at Syracuse"),
  ("Rhegium","Acts 28:13","To Rhegium"),
  ("Puteoli","Acts 28:13","Brethren found at Puteoli"),
  ("Appii forum","Acts 28:15","The brethren meet him"),
  ("Rome","Acts 28:16","Two whole years in his own hired house"),
 ]),
}
