# The Bible journeys — approved stop list (FBC, Oct 2026). Built into journeys.json by build.py.
# Stop: (place name as in places.json, verse naming it, what happened[, label as the verse spells it[, opts]])
#   opts: ll=[lat,lon] draw here instead (the traditional site); sure=False dashed; site='…' shown under the stop;
#         toward=[lat,lon,label] a dotted arrow off the route; ev='timeline title' when the chapter's own entry is not this event; alts=[(label,[lat,lon]),…] several suggested sites, dotted (no place in the data)
# ("~", lat, lon): a route point only (coasts, rivers), not a stop. Lines bend through it.
J = {
 "abraham": ("Abraham's journey", "Genesis 11–25", [
  ("Ur","Genesis 11:31","Terah takes Abram out of Ur of the Chaldees",None,dict(site="Tell el-Muqayyar in southern Iraq, dug by Leonard Woolley from 1922 — the usual identification")),
  ("~",32.54,44.42), ("~",34.55,40.89), ("~",35.95,39.0),
  ("Haran","Genesis 11:31","They come to Haran and dwell there"),
  ("~",36.2,37.15), ("~",33.5,36.3),
  ("Shechem","Genesis 12:6","Abram passes through the land unto Sichem"),
  ("Bethel","Genesis 12:8","An altar between Bethel and Hai"),
  ("Egypt","Genesis 12:10","Down into Egypt in the famine"),
  ("Bethel","Genesis 13:3","Back to the place of the altar"),
  ("Hebron","Genesis 13:18","He dwells in the plain of Mamre"),
  ("Dan","Genesis 14:14","He pursues the kings unto Dan"),
  ("Hobah","Genesis 14:15","Hobah, on the left hand of Damascus"),
  ("Salem","Genesis 14:18","Melchizedek king of Salem"),
  ("Gerar","Genesis 20:1","He sojourns in Gerar"),
  ("Beersheba","Genesis 21:31","The well of the oath"),
  ("Moriah","Genesis 22:2","Get thee into the land of Moriah"),
  ("Beersheba","Genesis 22:19","They return to Beersheba"),
  ("Hebron","Genesis 23:19","Sarah buried in the cave of Machpelah"),
 ]),
 "jacob": ("Jacob's journey", "Genesis 28–35, 46", [
  ("Beersheba","Genesis 28:10","Jacob goes out from Beersheba"),
  ("Bethel","Genesis 28:19","The ladder; he calls the place Bethel"),
  ("~",33.5,36.3), ("~",36.2,37.15),
  ("Haran","Genesis 29:4","Twenty years with Laban"),
  ("~",36.2,37.15), ("~",33.5,36.3),
  ("Gilead","Genesis 31:25","Laban overtakes him in mount Gilead"),
  ("Mahanaim","Genesis 32:2","The angels of God meet him"),
  ("Peniel","Genesis 32:30","He wrestles until the breaking of the day"),
  ("Succoth","Genesis 33:17","He builds booths"),
  ("Shechem","Genesis 33:18","He comes to Shalem, a city of Shechem"),
  ("Bethel","Genesis 35:6","He builds an altar at Bethel"),
  ("Bethlehem","Genesis 35:19","Rachel dies on the way to Ephrath"),
  ("Hebron","Genesis 35:27","He comes unto Isaac at Mamre"),
  ("Beersheba","Genesis 46:1","Sacrifices on the way to Egypt"),
  ("Goshen","Genesis 46:28","Joseph meets him in Goshen"),
 ]),
 "joseph": ("Joseph sold into Egypt", "Genesis 37", [
  ("Hebron","Genesis 37:14","Sent out of the vale of Hebron"),
  ("Shechem","Genesis 37:14","To see his brethren at Shechem"),
  ("Dothan","Genesis 37:17","He finds them in Dothan"),
  ("Egypt","Genesis 37:28","Sold to the Ishmeelites and brought into Egypt"),
 ]),
 "exodus": ("The Exodus & the wilderness", "Exodus 12 – Deuteronomy 34", [
  ("Rameses","Exodus 12:37","Israel journeys from Rameses"),
  ("Succoth","Exodus 12:37","To Succoth"),
  ("Etham","Exodus 13:20","Encamped in Etham, in the edge of the wilderness"),
  ("Pi-hahiroth","Exodus 14:2","Before Pi-hahiroth — the Red Sea is parted",None,dict(ll=[29.97,32.56],sure=False,site="The crossing as the traditional maps show it, at the head of the Gulf of Suez")),
  ("Marah","Exodus 15:23","The bitter waters made sweet"),
  ("Elim","Exodus 15:27","Twelve wells and seventy palm trees"),
  ("Sin","Exodus 16:1","The wilderness of Sin — manna given"),
  ("Rephidim","Exodus 17:1","Water from the rock; Amalek fought"),
  ("Mount Sinai","Exodus 19:20","The LORD comes down upon mount Sinai",None,dict(site="Jebel Musa in the south of the Sinai peninsula, the site kept since the 300s (St Catherine's monastery)")),
  ("Kibroth-hattaavah","Numbers 11:34","The graves of lust"),
  ("Hazeroth","Numbers 11:35","Miriam's leprosy"),
  ("Kadesh","Numbers 13:26","The spies return; forty years decreed"),
  ("Ezion-geber","Numbers 33:35","Encamped at Ezion-gaber"),
  ("Hor","Numbers 20:27","Aaron dies in mount Hor",None,dict(ll=[30.3172,35.4072],sure=False,site="Jebel Harun near Petra, the traditional mount Hor")),
  ("Punon","Numbers 33:42","Encamped in Punon"),
  ("Arnon","Numbers 21:13","Beyond Arnon, the border of Moab"),
  ("Heshbon","Numbers 21:26","Sihon's city taken"),
  ("Plains of Moab","Numbers 22:1","The plains of Moab by Jordan near Jericho"),
  ("Nebo","Deuteronomy 34:1","Moses sees the land and dies"),
 ]),
 "david": ("David fleeing Saul", "1 Samuel 19–27", [
  ("Gibeah","1 Samuel 22:6","Saul abides in Gibeah"),
  ("Ramah","1 Samuel 19:18","David escapes to Samuel at Ramah"),
  ("Nob","1 Samuel 21:1","Ahimelech gives him the shewbread"),
  ("Gath","1 Samuel 21:10","He flees to Achish king of Gath"),
  ("Adullam","1 Samuel 22:1","The cave Adullam"),
  ("Mizpeh","1 Samuel 22:3","Mizpeh of Moab"),
  ("Hareth","1 Samuel 22:5","The forest of Hareth"),
  ("Keilah","1 Samuel 23:5","He saves Keilah"),
  ("Wilderness of Ziph","1 Samuel 23:14","The wilderness of Ziph"),
  ("Wilderness of Maon","1 Samuel 23:25","The wilderness of Maon"),
  ("Engedi","1 Samuel 24:1","He spares Saul in the cave"),
  ("Carmel","1 Samuel 25:2","Nabal and Abigail"),
  ("Gath","1 Samuel 27:2","Back to Achish"),
  ("Ziklag","1 Samuel 27:6","Achish gives him Ziklag"),
 ]),
 "elijah": ("Elijah", "1 Kings 17 – 2 Kings 2", [
  ("Tishbite","1 Kings 17:1","Elijah the Tishbite"),
  ("Cherith","1 Kings 17:3","Fed by ravens at the brook"),
  ("Zarephath","1 Kings 17:9","The widow's meal and oil"),
  ("Carmel","1 Kings 18:20","Fire from heaven on mount Carmel"),
  ("Kishon","1 Kings 18:40","The prophets of Baal slain"),
  ("Jezreel","1 Kings 18:46","He runs before Ahab to Jezreel"),
  ("Beersheba","1 Kings 19:3","He flees for his life"),
  ("Horeb","1 Kings 19:8","The still small voice",None,dict(site="Jebel Musa in the south of the Sinai peninsula, the site kept since the 300s")),
  ("Abel-meholah","1 Kings 19:16","Elisha of Abel-meholah called"),
  ("Gilgal","2 Kings 2:1","With Elisha from Gilgal"),
  ("Bethel","2 Kings 2:2","To Bethel"),
  ("Jericho","2 Kings 2:4","To Jericho"),
  ("Jordan","2 Kings 2:7","Taken up by a whirlwind beyond Jordan"),
 ]),
 "jonah": ("Jonah", "Jonah 1–4", [
  ("Gath-hepher","2 Kings 14:25","Jonah the prophet, of Gath-hepher"),
  ("Joppa","Jonah 1:3","He takes ship at Joppa, fleeing toward Tarshish",None,dict(toward=[32.6,31.3,"toward Tarshish"])),
  ("~",33.5,36.3), ("~",36.2,37.15), ("~",36.83,38.02),
  ("Nineveh","Jonah 3:3","Nineveh, that great city, repents",None,dict(sure=False,site="Cast out upon the dry land — the place is not told")),
 ]),
 "captivity": ("Carried away to Babylon", "2 Kings 24–25; Daniel 1", [
  ("Jerusalem","2 Kings 25:9","The house of the LORD burnt"),
  ("Riblah","2 Kings 25:6","Zedekiah judged at Riblah"),
  ("~",36.2,37.15), ("~",36.83,38.02), ("~",35.95,39.0), ("~",34.55,40.89),
  ("Babylon","2 Kings 25:11","The people carried away to Babylon"),
  ("Chebar","Ezekiel 1:1","Ezekiel among the captives by the river Chebar"),
  ("Shushan","Daniel 8:2","Daniel's vision at Shushan the palace"),
 ]),
 "return": ("The return from captivity", "Ezra – Nehemiah", [
  ("Babylon","Ezra 1:11","Cyrus sends them up from Babylon"),
  ("Ahava","Ezra 8:15","Ezra gathers them by the river Ahava"),
  ("~",34.55,40.89), ("~",35.95,39.0), ("~",36.83,38.02), ("~",36.2,37.15), ("~",33.5,36.3),
  ("Jerusalem","Ezra 8:32","They come to Jerusalem"),
  ("~",33.5,36.3), ("~",36.2,37.15), ("~",36.83,38.02), ("~",35.95,39.0), ("~",34.55,40.89), ("~",32.54,44.42),
  ("Shushan","Nehemiah 1:1","Nehemiah in Shushan the palace"),
  ("~",32.54,44.42), ("~",34.55,40.89), ("~",35.95,39.0), ("~",36.83,38.02), ("~",36.2,37.15), ("~",33.5,36.3),
  ("Jerusalem","Nehemiah 2:11","Nehemiah comes to Jerusalem and builds the wall"),
 ]),
 "childhood": ("The birth and childhood of Jesus", "Matthew 2; Luke 2", [
  ("Nazareth","Luke 2:4","Joseph goes up from Nazareth"),
  ("Bethlehem","Luke 2:4","The Saviour born in Bethlehem"),
  ("Jerusalem","Luke 2:22","Presented to the Lord in the temple"),
  ("Egypt","Matthew 2:14","The flight into Egypt"),
  ("Nazareth","Matthew 2:23","He dwells in Nazareth"),
  ("Jerusalem","Luke 2:42","In the temple at twelve years old",None,dict(ev="Jesus in the temple at twelve")),
 ]),
 "ministry": ("Jesus' ministry", "the Gospels", [
  ("Bethabara","John 1:28","Baptized beyond Jordan"),
  ("Cana","John 2:1","Water made wine"),
  ("Capernaum","John 2:12","Down to Capernaum"),
  ("Jerusalem","John 2:13","The temple cleansed; Nicodemus"),
  ("Sychar","John 4:5","The woman at the well"),
  ("Cana","John 4:46","The nobleman's son healed"),
  ("Nazareth","Luke 4:16","Rejected in his own synagogue"),
  ("Capernaum","Matthew 4:13","He dwells in Capernaum"),
  ("@","Matthew 5:1","The sermon on the mount","The sermon on the mount",dict(ll=[32.881,35.556],sure=False,site="“He went up into a mountain” — the Mount of Beatitudes is the traditional site")),
  ("Nain","Luke 7:11","The widow's son raised"),
  ("Gadarenes","Mark 5:1","The man with the legion"),
  ("Bethsaida","Luke 9:10","Five thousand fed",None,dict(ev="Five thousand fed")),
  ("Tyre","Mark 7:24","The Syrophenician woman"),
  ("Sidon","Mark 7:31","Through the coasts of Tyre and Sidon"),
  ("Caesarea Philippi","Matthew 16:13","“Thou art the Christ”"),
  ("@","Matthew 17:1","The transfiguration","An high mountain apart",dict(alts=[("Mount Hermon?",[33.416,35.857]),("Mount Tabor?",[32.686,35.393])],site="The mountain is not named — Hermon and Tabor are the two suggested")),
  ("Capernaum","Matthew 17:24","The tribute money"),
  ("Bethany","John 11:1","Lazarus raised"),
  ("Ephraim","John 11:54","He goes to a city called Ephraim"),
 ]),
 "passion": ("The last week & the resurrection", "the Gospels; Acts 1", [
  ("Jericho","Luke 19:1","Zacchaeus"),
  ("Bethany","John 12:1","Six days before the passover"),
  ("Bethphage","Matthew 21:1","The colt brought from Bethphage"),
  ("Jerusalem","Matthew 21:10","The triumphal entry"),
  ("Gethsemane","Matthew 26:36","He prays in the garden"),
  ("Golgotha","John 19:17","Crucified at the place of a skull",None,dict(site="The Church of the Holy Sepulchre, inside today's walls but outside the wall of Jesus' day")),
  ("Emmaus","Luke 24:13","The road to Emmaus"),
  ("Sea of Galilee","John 21:1","He shows himself by the sea"),
  ("Mount of Olives","Acts 1:12","Taken up from the mount called Olivet"),
 ]),
 "paul0": ("Saul's conversion", "Acts 9, 11; Galatians 1", [
  ("Jerusalem","Acts 9:2","Breathing out threatenings"),
  ("Damascus","Acts 9:3","A light from heaven"),
  ("Arabia","Galatians 1:17","I went into Arabia",None,dict(sure=False)),
  ("Damascus","Acts 9:22","Let down by the wall in a basket"),
  ("Jerusalem","Acts 9:26","Barnabas brings him to the apostles"),
  ("Caesarea","Acts 9:30","Brought down to Caesarea"),
  ("Tarsus","Acts 9:30","Sent forth to Tarsus"),
  ("Antioch","Acts 11:26","Called Christians first in Antioch"),
 ]),
 "peter": ("Philip and Peter", "Acts 8–10", [
  ("Jerusalem","Acts 8:1","The church scattered"),
  ("Samaria","Acts 8:5","Philip preaches Christ in Samaria"),
  ("Gaza","Acts 8:26","The way that goeth down unto Gaza — the eunuch"),
  ("Ashdod","Acts 8:40","Philip found at Azotus","Azotus"),
  ("Lod","Acts 9:32","Peter heals Aeneas","Lydda"),
  ("Joppa","Acts 9:36","Dorcas raised"),
  ("Caesarea","Acts 10:24","Cornelius and his house saved"),
 ]),
 "paul1": ("Paul's first journey", "Acts 13–14", [
  ("Antioch","Acts 13:1","Separated for the work"),
  ("Seleucia","Acts 13:4","Down to Seleucia"),
  ("Salamis","Acts 13:5","Preaching in the synagogues"),
  ("Paphos","Acts 13:6","Elymas the sorcerer blinded"),
  ("Perga","Acts 13:13","John departs from them"),
  ("Antioch","Acts 13:14","“Lo, we turn to the Gentiles”","Antioch in Pisidia"),
  ("Iconium","Acts 13:51","A great multitude believe"),
  ("Lystra","Acts 14:8","The cripple healed; Paul stoned"),
  ("Derbe","Acts 14:20","Many taught"),
  ("Lystra","Acts 14:21","Confirming the souls of the disciples"),
  ("Attalia","Acts 14:25","Down into Attalia"),
  ("Antioch","Acts 14:26","Back to Antioch"),
 ]),
 "paul2": ("Paul's second journey", "Acts 15:36 – 18:22", [
  ("Antioch","Acts 15:35","Paul and Silas set out"),
  ("Derbe","Acts 16:1","Timothy joins them"),
  ("Troas","Acts 16:8","The vision of the man of Macedonia"),
  ("Samothracia","Acts 16:11","A straight course to Samothracia"),
  ("Neapolis","Acts 16:11","To Neapolis"),
  ("Philippi","Acts 16:12","Lydia; the jailer saved"),
  ("Amphipolis","Acts 17:1","Through Amphipolis"),
  ("Thessalonica","Acts 17:1","Three sabbath days reasoning"),
  ("Berea","Acts 17:10","They searched the scriptures daily"),
  ("Athens","Acts 17:22","Mars' hill"),
  ("Corinth","Acts 18:1","A year and six months"),
  ("Cenchrea","Acts 18:18","Shorn his head at Cenchrea"),
  ("Ephesus","Acts 18:19","Reasoning with the Jews"),
  ("~",36.4,28.2), ("~",34.3,32.0),
  ("Caesarea","Acts 18:22","Landed at Caesarea"),
  ("Antioch","Acts 18:22","Down to Antioch"),
 ]),
 "paul3": ("Paul's third journey", "Acts 18:23 – 21:17", [
  ("Antioch","Acts 18:22","Some time at Antioch"),
  ("Ephesus","Acts 19:1","Two years; the uproar of Diana"),
  ("Philippi","Acts 20:6","Through Macedonia and Greece, then sail from Philippi"),
  ("Troas","Acts 20:6","Eutychus raised"),
  ("Assos","Acts 20:13","Paul goes afoot to Assos"),
  ("Mitylene","Acts 20:14","To Mitylene"),
  ("Miletus","Acts 20:17","Farewell to the Ephesian elders"),
  ("Coos","Acts 21:1","A straight course unto Coos"),
  ("Rhodes","Acts 21:1","To Rhodes"),
  ("Patara","Acts 21:1","To Patara"),
  ("~",34.3,32.4),
  ("Tyre","Acts 21:3","Seven days with the disciples"),
  ("Ptolemais","Acts 21:7","To Ptolemais"),
  ("Caesarea","Acts 21:8","Philip's house; Agabus"),
  ("Jerusalem","Acts 21:17","Received gladly"),
 ]),
 "rome": ("Paul's voyage to Rome", "Acts 21–28", [
  ("Jerusalem","Acts 21:31","Paul taken in the temple"),
  ("Aphek","Acts 23:31","Brought by night to Antipatris","Antipatris"),
  ("Caesarea","Acts 23:33","Two years before Felix and Festus"),
  ("Sidon","Acts 27:3","Julius lets him visit his friends"),
  ("~",35.75,33.6), ("~",36.0,31.5),
  ("Myra","Acts 27:5","A ship of Alexandria"),
  ("Cnidus","Acts 27:7","Scarce come over against Cnidus"),
  ("Salmone","Acts 27:7","Under Crete, over against Salmone"),
  ("~",34.95,26.1),
  ("The fair havens","Acts 27:8","Near the city of Lasea"),
  ("Clauda","Acts 27:16","Under the island Clauda — the storm"),
  ("Melita","Acts 28:1","Shipwrecked on Melita",None,dict(ev="Shipwreck on the way to Rome",ll=[35.951,14.408],site="St Paul's Bay, where St Paul's Islands make “a place where two seas met” (Acts 27:41)")),
  ("Syracuse","Acts 28:12","Three days at Syracuse",None,dict(ev="Shipwreck on the way to Rome")),
  ("Rhegium","Acts 28:13","To Rhegium",None,dict(ev="Shipwreck on the way to Rome")),
  ("Puteoli","Acts 28:13","Brethren found at Puteoli",None,dict(ev="Shipwreck on the way to Rome")),
  ("Appii forum","Acts 28:15","The brethren meet him",None,dict(ev="Shipwreck on the way to Rome")),
  ("Rome","Acts 28:16","Two whole years in his own hired house"),
 ]),
}

# Disputed sites. Each group is one question ("where is mount Sinai?") with its views, shown as a switch on
# every journey stop and place page it touches; the choice is shared, so the Exodus and Elijah always agree.
#   t: the question; default: the view shown first (the literal reading of the text, where the views split
#   that way, over a site fixed by later church tradition); views: (label, why, {place id: (site, [lat,lon])}).
GROUPS = {
 "sinai": dict(t="Red Sea & Sinai", default=1, views=[
  ("Suez / Peninsula Route",
   "The crossing at the head of the Gulf of Suez, and mount Sinai at Jebel Musa in the south of the Sinai peninsula. This is the Byzantine tradition, "
   "kept since the 300s (the time of Helena, Constantine's mother), when monks settled at the mountain; Justinian built St Catherine's monastery at its foot "
   "in the 500s. It leaves room for the many camps of Numbers 33 between the sea and Sinai.",
   {"abfba2a": ("Jebel Musa", [28.53972,33.97333]), "a9bb03e": ("Jebel Musa", [28.53972,33.97333]),
    "ababfd2": ("The head of the Gulf of Suez", [29.97,32.56]), "ac2cef0": ("Ain el-Qudeirat", [30.64833,34.42222])}),
  ("Aqaba / Arabian Route",
   "Israel crosses the Sinai peninsula and the Gulf of Aqaba at Nuweiba Beach, and mount Sinai is Jabal al-Lawz in Midian. "
   "Moses kept Jethro's flock in Midian when he came to Horeb (Exodus 2:15; 3:1); Paul writes of “mount Sinai in Arabia” (Galatians 4:25); "
   "the Sinai peninsula was held by Egypt's garrisons and mines; and Kadesh is Petra, “a city in the uttermost of thy border” of Edom (Numbers 20:16). "
   "The usual route follows the Byzantine tradition of Jebel Musa; this one follows the text placing Sinai in Midian and Arabia.",
   {"abfba2a": ("Jabal al-Lawz", [28.654,35.305]), "a9bb03e": ("Jabal al-Lawz", [28.654,35.305]),
    "ababfd2": ("Nuweiba Beach", [28.97,34.66]), "ac2cef0": ("Petra", [30.3285,35.4444])}),
 ]),
 "ur": dict(t="Ur of the Chaldees", default=1, views=[
  ("Ur of Tell el-Muqayyar",
   "The great Sumerian city in southern Iraq, dug by Leonard Woolley from 1922 and named Abraham's Ur after; the Chaldeans of later times ruled that region.",
   {"a6cf75c": ("Tell el-Muqayyar", [30.96222,46.10444])}),
  ("Ur of Urfa / Şanlıurfa",
   "Ur of the Chaldees is Urfa (Şanlıurfa, historically Edessa) in southern Turkey, a short way from Haran. Then Haran lies on the road from Ur to Canaan "
   "rather than 600 miles the wrong way; and when Abraham sends to “my country, and to my kindred” the servant goes to Mesopotamia, "
   "to the city of Nahor by Haran (Genesis 24:4, 10).",
   {"a6cf75c": ("Urfa (Şanlıurfa)", [37.159,38.797])}),
 ]),
 "golgotha": dict(t="Golgotha & the tomb", default=1, views=[
  ("Church of the Holy Sepulchre",
   "The site Constantine's builders uncovered in 326 under a temple of Venus, by the tradition of the Jerusalem church; Helena's visit is tied to it. "
   "It lies inside today's walls, but outside the wall of Jesus' day, and tombs of that time are cut in the rock there.",
   {"a631d35": ("Church of the Holy Sepulchre", [31.77844,35.22975])}),
  ("Garden Tomb (Gordon's Calvary)",
   "A skull-like rock face north of the Damascus Gate, outside the wall, with a garden and a rock-cut tomb beside it: “without the gate” (Hebrews 13:12), "
   "“nigh to the city” (John 19:20), and “in the place where he was crucified there was a garden; and in the garden a new sepulchre” (John 19:41). "
   "Suggested by Otto Thenius in 1842 and made known by General Charles Gordon in 1883.",
   {"a631d35": ("The Garden Tomb", [31.7839,35.2298])}),
 ]),
 "emmaus": dict(t="Emmaus", default=1, views=[
  ("Motza (Qalunya)",
   "The Emmaus of Josephus, where Vespasian settled his soldiers, about 4 miles from Jerusalem — held by many scholars, though nearer than threescore furlongs.",
   {"ae7274b": ("Qalunya (Motza)", [31.79289,35.16419])}),
  ("Threescore furlongs (el-Qubeibeh)",
   "Emmaus was “from Jerusalem about threescore furlongs” (Luke 24:13), about seven miles; el-Qubeibeh lies that far northwest of Jerusalem, on the Roman road. "
   "The Crusaders knew it as Emmaus.",
   {"ae7274b": ("el-Qubeibeh", [31.83993,35.13685])}),
  ("Emmaus Nicopolis",
   "The Byzantine site, about 19 miles away. It needs “an hundred and threescore furlongs”, found in a few old Greek copies; the Greek text of the KJV reads threescore, "
   "and the two walked there and back the same evening (Luke 24:29, 33).",
   {"ae7274b": ("Emmaus Nicopolis", [31.8393,34.98946])}),
 ]),
 "bethsaida": dict(t="Bethsaida", default=0, views=[
  ("et-Tell",
   "A mound about a mile and a half from the shore, east of where the Jordan flows in, dug since 1987; held to be Bethsaida Julias, rebuilt by Philip the tetrarch.",
   {"a91b732": ("et-Tell", [32.91038,35.63096]), "a9fc13a": ("et-Tell", [32.91038,35.63096])}),
  ("el-Araj",
   "On the shore itself, as a fishing town should be — “Bethsaida, the city of Andrew and Peter” (John 1:44). Digs since 2016 have found a town of Roman times "
   "and a Byzantine church that may be the one pilgrims said stood over the apostles' house.",
   {"a91b732": ("el-Araj", [32.89353,35.619]), "a9fc13a": ("el-Araj", [32.89353,35.619])}),
 ]),
 "melita": dict(t="Paul's shipwreck", default=0, views=[
  ("St Paul's Bay",
   "The bay in the north of Malta named for Paul; St Paul's Islands at its mouth make “a place where two seas met” (Acts 27:41). In 1848 James Smith, "
   "a Scottish yachtsman, checked Luke's soundings of twenty and fifteen fathoms (27:28) and the drift from Clauda against the charts, and found they fit this bay.",
   {"a57835d": ("St Paul's Bay", [35.951,14.408])}),
  ("St Thomas Bay",
   "Robert Cornuke's view (2003): the soundings, a reef and a sandbank between two currents fit St Thomas Bay in the southeast of Malta, "
   "where he reported Roman anchors brought up by divers.",
   {"a57835d": ("St Thomas Bay", [35.852,14.567])}),
 ]),
 # Places only (not journey stops)
 "ai": dict(t="Ai", default=1, views=[
  ("et-Tell",
   "The usual identification since Edward Robinson (1838): a large mound east of Beitin. But it lay empty from about 2400 to 1200 B.C., "
   "so those who hold it mostly say the account of Joshua 7–8 is not history.",
   {"a7e13e1": ("et-Tell", [31.91694,35.26111]), "a63c70b": ("et-Tell", [31.91694,35.26111])}),
  ("Khirbet el-Maqatir",
   "Dug from 1995 by Bryant Wood and the Associates for Biblical Research: a small fortress of Joshua's time that was burned, with its gate on the north "
   "(Joshua 8:11), “beside Bethaven, on the east side of Bethel” (7:2) — fitting the conquest about 1400 B.C.",
   {"a7e13e1": ("Khirbet el-Maqatir", [31.91476,35.2496]), "a63c70b": ("Khirbet el-Maqatir", [31.91476,35.2496])}),
 ]),
 "sodom": dict(t="Sodom & Gomorrah", default=1, views=[
  ("South of the Dead Sea",
   "The usual view: the cities lay by the Lisan and the southern basin, near Zoar (Genesis 19:22), where Bab edh-Dhra and Numeira are towns of early times that were burned. "
   "Bryant Wood and other conservative scholars hold this view.",
   {"a0aa664": ("Bab edh-Dhra", [31.24873,35.523]), "aa572e2": ("Numeira", [31.12976,35.52937])}),
  ("North of the Dead Sea (Tall el-Hammam)",
   "From near Bethel Lot “beheld all the plain of Jordan, that it was well watered every where” (Genesis 13:10) — the plain north of the Dead Sea, in sight of Bethel. "
   "Steven Collins has dug Tall el-Hammam there since 2005: a great walled city of Abraham's time, destroyed suddenly by fire.",
   {"a0aa664": ("Tall el-Hammam", [31.8406,35.6739]), "aa572e2": ("North of the Dead Sea", [31.795,35.59528])}),
 ]),
 "ararat": dict(t="Where the ark rested", default=0, views=[
  ("Mount Ararat (Ağrı Dağı)",
   "The ark rested “upon the mountains of Ararat” (Genesis 8:4) — Urartu, the highlands of eastern Turkey and Armenia. Its highest peak (16,854 ft) "
   "is where most who search for the ark have looked.",
   {"ab89be9": ("Mount Ararat", [39.7019,44.2983])}),
  ("Durupınar site",
   "A boat-shaped formation about 18 miles south of the peak, made known by Ron Wyatt in the 1980s; most creationist geologists hold it is a natural formation.",
   {"ab89be9": ("Durupınar", [39.4406,44.2347])}),
  ("Mount Judi (Cudi Dağı)",
   "The Syriac and Islamic tradition, in the mountains of southeast Turkey above the Tigris; Josephus, quoting Berossus, tells of remains of the ark in the mountains of the Cordyaeans.",
   {"ab89be9": ("Cudi Dağı", [37.38,42.45])}),
 ]),
 "hor": dict(t="Mount Hor", default=0, views=[
  ("Jebel Harun",
   "Above Petra, crowned by a shrine to Aaron — the site Josephus knew, and the usual one. With Kadesh at Petra (the Aqaba / Arabian Route) it is close by.",
   {"ad8027f": ("Jebel Harun", [30.3172,35.4072])}),
  ("Near Kadesh, on Edom's edge",
   "Hor was “by the coast of the land of Edom” and “in the edge of the land of Edom” (Numbers 20:23; 33:37), one march from Kadesh with all the congregation (20:22); "
   "with Kadesh in the Negev, many look for it northeast of Kadesh (often Jebel Madurah) rather than in the heart of Edom.",
   {"ad8027f": ("Northeast of Kadesh", [30.83206,35.05687])}),
 ]),
}
# Each journey's other views, per group: {view index: the whole stop list for that view} — stops as in J.
# A view must keep the same stops in the same order; only the stops it moves differ.
def swap(stops, name, ref, **o):
    out = [st for st in stops]
    i = next(i for i, st in enumerate(out) if st[0] == name and st[1] == ref)
    out[i] = out[i][:3] + (None, o)
    return out
_ex, _ab = J["exodus"][2], J["abraham"][2]
VIEWS = {
 "exodus": {"sinai": {1: _ex[:3] + [
  ("~",30.1,33.1), ("~",29.55,34.2), ("~",29.06,34.58),
  ("Pi-hahiroth","Exodus 14:2","Before Pi-hahiroth — the Red Sea is parted",None,dict(ll=[28.97,34.66],sure=False,site="Nuweiba Beach on the Gulf of Aqaba, shut in by mountains with one wadi in (Exodus 14:3) — the crossing in this view")),
  ("~",28.93,34.78),
  ("Marah","Exodus 15:23","The bitter waters made sweet",None,dict(ll=[28.8,34.87],sure=False,site="On the Arabian shore, in Midian — the site is not known")),
  ("Elim","Exodus 15:27","Twelve wells and seventy palm trees",None,dict(ll=[28.49,35.02],sure=False,site="Often placed at the springs of al-Bad', where local tradition remembers Jethro")),
  ("Sin","Exodus 16:1","The wilderness of Sin — manna given",None,dict(ll=[28.56,35.16],sure=False,site="Between the coast and the mountain — the site is not known")),
  ("Rephidim","Exodus 17:1","Water from the rock; Amalek fought",None,dict(ll=[28.62,35.25],sure=False,site="Near the split rock of Jabal Maqla, below Jabal al-Lawz")),
  ("Mount Sinai","Exodus 19:20","The LORD comes down upon mount Sinai",None,dict(ll=[28.654,35.305],sure=False,site="Jabal al-Lawz in northwest Saudi Arabia — “mount Sinai in Arabia” (Galatians 4:25)")),
  ("Kibroth-hattaavah","Numbers 11:34","The graves of lust",None,dict(ll=[28.95,35.32],sure=False,site="On the way north from the mount — the site is not known")),
  ("Hazeroth","Numbers 11:35","Miriam's leprosy",None,dict(ll=[29.25,35.15],sure=False,site="On the way north from the mount — the site is not known")),
  ("Kadesh","Numbers 13:26","The spies return; forty years decreed",None,dict(ll=[30.3285,35.4444],sure=False,site="Petra, “a city in the uttermost of thy border” of Edom (Numbers 20:16) — Kadesh in this view")),
 ] + _ex[12:]}},
 "elijah": {"sinai": {1: swap(J["elijah"][2], "Horeb", "1 Kings 19:8", ll=[28.654,35.305], sure=False,
   site="Jabal al-Lawz in Midian — the mount of God in the Aqaba / Arabian view (Galatians 4:25)")}},
 "abraham": {"ur": {1: [
  ("Ur","Genesis 11:31","Terah takes Abram out of Ur of the Chaldees",None,dict(ll=[37.159,38.797],sure=False,site="Urfa (Şanlıurfa, historically Edessa) in southern Turkey — the northern Ur, a day or two from Haran")),
 ] + _ab[4:]}},
 "passion": {
  "golgotha": {1: swap(J["passion"][2], "Golgotha", "John 19:17", ll=[31.7839,35.2298], site="The Garden Tomb and Gordon's Calvary, north of the Damascus Gate — outside the wall, with a garden and a new tomb (John 19:41)")},
  "emmaus": {1: swap(J["passion"][2], "Emmaus", "Luke 24:13", ll=[31.83993,35.13685], sure=False, site="el-Qubeibeh, about threescore furlongs (seven miles) from Jerusalem"),
             2: swap(J["passion"][2], "Emmaus", "Luke 24:13", ll=[31.8393,34.98946], sure=False, site="Emmaus Nicopolis, the Byzantine site, about 19 miles from Jerusalem")}},
 "ministry": {"bethsaida": {1: swap(J["ministry"][2], "Bethsaida", "Luke 9:10", ll=[32.89353,35.619], sure=False, ev="Five thousand fed", site="el-Araj, on the shore of the sea")}},
 "rome": {"melita": {1: swap(J["rome"][2], "Melita", "Acts 28:1", ll=[35.852,14.567], sure=False, ev="Shipwreck on the way to Rome", site="St Thomas Bay in the southeast of Malta")}},
}
